---
apiVersion: v1
kind: Deployment
metadata:
  name: postgres
  namespace: "{{ project_name }}"
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRESQL_DATABASE
              value: pulp
            - name: POSTGRESQL_USER
              value: pulp
            - name: POSTGRESQL_PASSWORD
              value: pulp
          volumeMounts:
            - readOnly: false
              mountPath: /var/lib/pgsql/data
              name: postgres-data
          image: registry.access.redhat.com/rhel8/postgresql-10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
