dist: xenial
sudo: required
services: docker
language: python
services:
  - docker
install:
  # Need /usr/bin/http script, so use sudo
  - sudo pip install httpie
  - pip install docker molecule openshift jmespath
  - .travis/k3s-install.sh
script: .travis/k3s.sh
