dist: xenial
sudo: required
services: docker
language: python
services:
  - docker
install:
  - pip install docker molecule openshift jmespath httpie
install: .travis/k3s-install.sh
script: .travis/k3s.sh
