apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pulps.example.com
spec:
  group: example.com
  names:
    kind: Pulp
    listKind: PulpList
    plural: pulps
    singular: pulp
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
