---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulp-file-storage
  namespace: "{{ project_name }}"
spec:
  resources:
    requests:
      storage: "{{ pulp_operator_config_map.resources[0].data.pulp_file_storage_size }}"
  accessModes:
    - "{{ pulp_operator_config_map.resources[0].data.pulp_file_storage_accessMode }}"
