---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pulp-server"
  namespace: "{{ project_name }}"
data:
  settings.py: |
    DATABASES = {
      'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pulp',
        'USER': 'pulp',
        'PASSWORD': 'pulp',
        'HOST': 'postgres',
        'PORT': '5432',
        'CONN_MAX_AGE': 0
      },
    }

    SECRET_KEY = "{{ secret_key }}"

    DEBUG: True

    REDIS_HOST = 'redis'
    REDIS_PORT =  6379
    REDIS_PASSWORD = ''
